// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJU5EeRxqmYSTLN4pptiJ3c9IQCgJi7hY',
    appId: '1:423723179960:web:1af6c06c1304b9f1ef394d',
    messagingSenderId: '423723179960',
    projectId: 'fir-tutorials-b7416',
    authDomain: 'fir-tutorials-b7416.firebaseapp.com',
    storageBucket: 'fir-tutorials-b7416.appspot.com',
    measurementId: 'G-7VP6RPLQY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdQGOIrcZXgg2HZ-LX1jUXbBVn3FYXHtI',
    appId: '1:423723179960:android:1a6b0ad66935415fef394d',
    messagingSenderId: '423723179960',
    projectId: 'fir-tutorials-b7416',
    storageBucket: 'fir-tutorials-b7416.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD85C-xOSgwovsqBW1fKFnMNZokT2Dh77c',
    appId: '1:423723179960:ios:57c044a1325ad8dfef394d',
    messagingSenderId: '423723179960',
    projectId: 'fir-tutorials-b7416',
    storageBucket: 'fir-tutorials-b7416.appspot.com',
    iosBundleId: 'com.example.firebaseTutorials',
  );

}